server:
  port: 6001
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: localhost
    port: 6379
    timeout: 5000ms
    password: root
    lettuce:
      pool:
        max-idle: 50
        max-wait: -1
        max-active: 50
        min-idle: 1
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB

    
