server:
  port: 6003
spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes: #配置路由路径
        - id: third-party
          uri: lb://third-party
          predicates:
            - Path=/gateway/thirdparty/**
          filters:
            - StripPrefix=1

        - id: identification
          uri: lb://identification
          predicates:
            - Path=/gateway/fish/**
          filters:
            - StripPrefix=1