-- fish_category: table
CREATE TABLE `fish_category` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '分类id',
  `name` varchar(50) NOT NULL COMMENT '分类名称',
  `parent_id` bigint NOT NULL COMMENT '父分类id',
  `level` int NOT NULL COMMENT '分类级别：0->1级；1->2级',
  `sort` int DEFAULT '0' COMMENT '分类排序',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=305 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='鱼类信息分类';


INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (100, '淡水', 0, 1, 1);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (101, '海水', 0, 1, 2);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (102, '其他', 0, 1, 3);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (103, '硬骨鱼纲', 100, 2, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (104, '软骨鱼纲', 101, 2, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (105, '硬骨鱼纲', 101, 2, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (106, '鲤形目', 103, 3, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (107, '丽鱼目', 103, 3, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (108, '鲇形目', 103, 3, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (109, '攀鲈目', 103, 3, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (110, '鲈形目', 103, 3, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (111, '真鲨目', 104, 3, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (112, '鲱形目', 105, 3, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (113, '仙女鱼目', 105, 3, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (114, '鳗鲡目', 105, 3, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (115, '鲇形目', 105, 3, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (116, '颌针鱼目', 105, 3, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (117, '鲻形目', 105, 3, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (118, '鲈形目', 105, 3, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (119, '鲉形目', 105, 3, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (120, '鲽形目', 105, 3, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (121, '鲀形目', 105, 3, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (122, '鲤科', 106, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (123, '丽鱼科', 107, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (124, '鲿科', 108, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (125, '鮰科', 108, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (126, '鲇科', 108, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (127, '鳢科', 109, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (128, '棘臀鱼科', 110, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (129, '真鲨科', 111, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (130, '鲱科', 112, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (131, '锯腹鳓科', 112, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (132, '鳀科', 112, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (133, '狗母鱼科', 113, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (134, '海鳝科', 114, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (135, '海鲶科', 115, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (136, '鳗鲶科', 115, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (137, '鱵科', 116, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (138, '鲻科', 117, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (139, '鮨科', 118, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (140, '鱚科', 118, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (141, '鲹科', 118, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (142, '石首鱼科', 118, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (143, '鲾科', 118, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (144, '银鲈科', 118, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (145, '鲷科', 118, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (146, '石鲈科', 118, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (147, '金线鱼科', 118, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (148, '鯻科', 118, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (149, '羊鱼科', 118, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (150, '白鲳科 ', 118, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (151, '金钱鱼科', 118, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (152, '马鲅科', 118, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (153, '䲗科', 118, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (154, '蓝子鱼科', 118, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (155, '魣科', 118, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (156, '鲳科', 118, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (157, '长鲳科', 118, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (158, '虾虎鱼科', 118, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (159, '毒鲉科', 119, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (160, '鲬科', 119, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (161, '冠鲽科', 120, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (162, '舌鳎科', 120, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (163, '鳎科', 120, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (164, '单角鲀科', 121, 4, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (165, '鲫属', 122, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (166, '罗非鱼属', 123, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (167, '黄颡鱼属', 124, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (168, '叉尾鮰属', 125, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (169, '鲇属', 126, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (170, '乌鳢属', 127, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (171, '黑鲈属', 128, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (172, '斜齿鲨属', 129, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (173, '小沙丁鱼属', 130, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (174, '鰶属', 130, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (175, '海鰶属', 130, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (176, '鳓属', 131, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (177, '棱鳀属', 132, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (178, '龙头鱼属', 133, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (179, '蛇鲻属', 133, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (180, '裸胸鳝属', 134, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (181, '褶囊海鲶属', 135, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (182, '鳗鲶属', 136, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (183, '鱵属', 137, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (184, '鲻属', 138, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (185, '莫鲻属', 138, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (186, '九棘鲈属', 139, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (187, '鱚属', 140, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (188, '鲳鲹属', 141, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (189, '副叶鲹属', 141, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (190, '圆鲹属', 141, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (191, '鲹属', 141, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (192, '黄鱼属', 142, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (193, '黄鳍牙䱛属', 142, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (194, '叫姑鱼属', 142, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (195, '枝鳔石首鱼属', 142, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (196, '项鲾属', 143, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (197, '卡拉鲾属', 143, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (198, '银鲈属', 144, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (199, '二长棘犁齿鲷属', 145, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (200, '棘鲷属', 145, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (201, '金头鲷属', 145, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (202, '平鲷属', 145, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (203, '石鲈属', 146, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (204, '胡椒鲷属', 146, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (205, '眶棘鲈属', 147, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (206, '金线鱼属', 147, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (207, '叉牙鯻属', 148, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (208, '鯻属', 148, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (209, '绯鲤属', 149, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (210, '副绯鲤属', 149, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (211, '燕鱼属', 150, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (212, '金钱鱼属', 151, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (213, '钱蝶鱼属', 151, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (214, '四指马鲅属', 152, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (215, '䲗属', 153, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (216, '蓝子鱼属', 154, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (217, '魣属', 155, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (218, '鲳属', 156, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (219, '刺鲳属', 157, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (220, '刺虾虎鱼属', 158, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (221, '细棘虾虎鱼属', 158, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (222, '粗头鲉属', 159, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (223, '棘线鲬属', 160, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (224, '条鳎属', 161, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (225, '舌鳎属', 162, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (226, '鳎属', 163, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (227, '单角革鲀属', 164, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (228, '单角鲀属', 164, 5, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (229, '鲫', 165, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (230, '尼罗罗非鱼', 166, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (231, '黄颡鱼', 167, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (232, '斑点叉尾鮰', 168, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (233, '鲇', 169, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (234, '乌鳢', 170, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (235, '大口黑鲈', 171, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (236, '尖头斜齿鲨', 172, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (237, '黑尾小沙丁', 173, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (238, '金色小沙丁', 173, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (239, '花鰶', 174, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (240, '圆吻海鰶', 175, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (241, '鳓', 176, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (242, '杜氏棱鳀', 177, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (243, '汉氏棱鳀', 177, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (244, '龙头鱼', 178, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (245, '多齿蛇鲻', 179, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (246, '匀斑裸胸鳝', 180, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (247, '内尔褶囊海鲶', 181, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (248, '线纹鳗鲇', 182, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (249, '乔氏鱵', 183, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (250, '鲻', 184, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (251, '佩氏莫鲻', 185, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (252, '横纹九棘鲈', 186, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (253, '少鳞鱚', 187, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (254, '多鳞鱚', 187, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (255, '阿纳鲳鲹', 188, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (256, '克氏副叶鲹', 189, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (257, '蓝圆鲹', 190, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (258, '珍鲹', 191, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (259, '大黄鱼', 192, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (260, '尖头黄鳍牙䱛', 193, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (261, '叫姑鱼', 194, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (262, '皮氏叫姑鱼', 194, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (263, '勒氏枝鳔石首鱼', 195, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (264, '布氏项鲾', 196, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (265, '颈斑项鲾', 196, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (266, '黑斑卡拉鲾', 197, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (267, '七带银鲈', 198, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (268, '长棘银鲈', 198, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (269, '二长棘犁齿鲷', 199, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (270, '黑棘鲷', 200, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (271, '黄鳍棘鲷', 200, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (272, '灰棘鲷', 200, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (273, '金头鲷', 201, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (274, '平鲷', 202, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (275, '点石鲈', 203, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (276, '少棘胡椒鲷', 204, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (277, '伏氏眶棘鲈', 205, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (278, '红棘金线鱼', 206, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (279, '金线鱼', 206, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (280, '深水金线鱼', 206, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (281, '六带叉牙鯻', 207, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (282, '细鳞鯻', 208, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (283, '黑斑绯鲤', 209, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (284, '双带副绯鲤', 210, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (285, '燕鱼', 211, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (286, '金钱鱼', 212, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (287, '多纹钱鲽鱼', 213, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (288, '多鳞四指马鲅', 214, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (289, '弯角䲗', 215, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (290, '褐蓝子鱼', 216, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (291, '点蓝子鱼', 216, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (292, '倒牙魣', 217, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (293, '银鲳', 218, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (294, '刺鲳', 219, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (295, '拟矛尾刺虾虎鱼', 220, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (296, '犬牙细棘虾虎鱼', 221, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (297, '瞻星粗头鲉', 222, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (298, '棘线鲬', 223, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (299, '带纹条鳎', 224, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (300, '斑头舌鳎', 225, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (301, '黑鳍舌鳎', 225, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (302, '卵鳎', 226, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (303, '单角革鲀', 227, 6, 0);
INSERT INTO fish.fish_category (id, name, parent_id, level, sort) VALUES (304, '中华单角鲀', 228, 6, 0);


-- fish_img: table
CREATE TABLE `fish_img` (
  `fish_id` bigint NOT NULL COMMENT '鱼类名称id',
  `img_path` varchar(500) NOT NULL COMMENT '鱼类图片路径'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='鱼类图片路径';

INSERT INTO `fish_img` VALUES (229, 'https://4b527230k9.zicp.fun/other/鲫.png');
INSERT INTO `fish_img` VALUES (230, 'https://4b527230k9.zicp.fun/other/尼罗罗非鱼.png');
INSERT INTO `fish_img` VALUES (231, 'https://4b527230k9.zicp.fun/other/黄颡鱼.png');
INSERT INTO `fish_img` VALUES (232, 'https://4b527230k9.zicp.fun/other/斑点叉尾鮰.png');
INSERT INTO `fish_img` VALUES (233, 'https://4b527230k9.zicp.fun/other/鲇.png');
INSERT INTO `fish_img` VALUES (234, 'https://4b527230k9.zicp.fun/other/乌鳢.png');
INSERT INTO `fish_img` VALUES (235, 'https://4b527230k9.zicp.fun/other/大口黑鲈.png');
INSERT INTO `fish_img` VALUES (236, 'https://4b527230k9.zicp.fun/other/尖头斜齿鲨.png');
INSERT INTO `fish_img` VALUES (237, 'https://4b527230k9.zicp.fun/other/黑尾小沙丁.jpg');
INSERT INTO `fish_img` VALUES (238, 'https://4b527230k9.zicp.fun/other/金色小沙丁.png');
INSERT INTO `fish_img` VALUES (239, 'https://4b527230k9.zicp.fun/other/花鰶.jpg');
INSERT INTO `fish_img` VALUES (240, 'https://4b527230k9.zicp.fun/other/圆吻海鰶.jpg');
INSERT INTO `fish_img` VALUES (241, 'https://4b527230k9.zicp.fun/other/鳓.png');
INSERT INTO `fish_img` VALUES (242, 'https://4b527230k9.zicp.fun/other/杜氏棱鳀.jpg');
INSERT INTO `fish_img` VALUES (243, 'https://4b527230k9.zicp.fun/other/汉氏棱鳀.jpg');
INSERT INTO `fish_img` VALUES (244, 'https://4b527230k9.zicp.fun/other/龙头鱼.jpg');
INSERT INTO `fish_img` VALUES (245, 'https://4b527230k9.zicp.fun/other/多齿蛇鲻.jpg');
INSERT INTO `fish_img` VALUES (246, 'https://4b527230k9.zicp.fun/other/匀斑裸胸鳝.png');
INSERT INTO `fish_img` VALUES (247, 'https://4b527230k9.zicp.fun/other/内尔褶囊海鲶.JPG');
INSERT INTO `fish_img` VALUES (248, 'https://4b527230k9.zicp.fun/other/线纹鳗鲇.jpg');
INSERT INTO `fish_img` VALUES (249, 'https://4b527230k9.zicp.fun/other/乔氏鱵.jpg');
INSERT INTO `fish_img` VALUES (250, 'https://4b527230k9.zicp.fun/other/鲻.jpg');
INSERT INTO `fish_img` VALUES (251, 'https://4b527230k9.zicp.fun/other/佩氏莫鲻.jpg');
INSERT INTO `fish_img` VALUES (252, 'https://4b527230k9.zicp.fun/other/横纹九棘鲈.JPG');
INSERT INTO `fish_img` VALUES (253, 'https://4b527230k9.zicp.fun/other/少鳞鱚.png');
INSERT INTO `fish_img` VALUES (254, 'https://4b527230k9.zicp.fun/other/多鳞鱚.png');
INSERT INTO `fish_img` VALUES (255, 'https://4b527230k9.zicp.fun/other/阿纳鲳鲹.jpg');
INSERT INTO `fish_img` VALUES (256, 'https://4b527230k9.zicp.fun/other/克氏副叶鲹.jpg');
INSERT INTO `fish_img` VALUES (257, 'https://4b527230k9.zicp.fun/other/蓝圆鲹.jpg');
INSERT INTO `fish_img` VALUES (258, 'https://4b527230k9.zicp.fun/other/珍鲹.jpg');
INSERT INTO `fish_img` VALUES (259, 'https://4b527230k9.zicp.fun/other/大黄鱼.jpg');
INSERT INTO `fish_img` VALUES (260, 'https://4b527230k9.zicp.fun/other/尖头黄鳍牙?.png');
INSERT INTO `fish_img` VALUES (261, 'https://4b527230k9.zicp.fun/other/叫姑鱼.png');
INSERT INTO `fish_img` VALUES (262, 'https://4b527230k9.zicp.fun/other/皮氏叫姑鱼.png');
INSERT INTO `fish_img` VALUES (263, 'https://4b527230k9.zicp.fun/other/勒氏枝鳔石首鱼.JPG');
INSERT INTO `fish_img` VALUES (264, 'https://4b527230k9.zicp.fun/other/布氏项鲾.png');
INSERT INTO `fish_img` VALUES (265, 'https://4b527230k9.zicp.fun/other/颈斑项鲾.jpg');
INSERT INTO `fish_img` VALUES (266, 'https://4b527230k9.zicp.fun/other/黑斑卡拉鲾.jpg');
INSERT INTO `fish_img` VALUES (267, 'https://4b527230k9.zicp.fun/other/七带银鲈.JPG');
INSERT INTO `fish_img` VALUES (268, 'https://4b527230k9.zicp.fun/other/长棘银鲈.jpg');
INSERT INTO `fish_img` VALUES (269, 'https://4b527230k9.zicp.fun/other/二长棘犁齿鲷.JPG');
INSERT INTO `fish_img` VALUES (270, 'https://4b527230k9.zicp.fun/other/黑棘鲷.jpg');
INSERT INTO `fish_img` VALUES (271, 'https://4b527230k9.zicp.fun/other/黄鳍棘鲷.jpg');
INSERT INTO `fish_img` VALUES (272, 'https://4b527230k9.zicp.fun/other/灰棘鲷.jpg');
INSERT INTO `fish_img` VALUES (273, 'https://4b527230k9.zicp.fun/other/金头鲷.jpg');
INSERT INTO `fish_img` VALUES (274, 'https://4b527230k9.zicp.fun/other/平鲷.jpg');
INSERT INTO `fish_img` VALUES (275, 'https://4b527230k9.zicp.fun/other/点石鲈.jpg');
INSERT INTO `fish_img` VALUES (276, 'https://4b527230k9.zicp.fun/other/少棘胡椒鲷.png');
INSERT INTO `fish_img` VALUES (277, 'https://4b527230k9.zicp.fun/other/伏氏眶棘鲈.jpg');
INSERT INTO `fish_img` VALUES (278, 'https://4b527230k9.zicp.fun/other/红棘金线鱼.jpg');
INSERT INTO `fish_img` VALUES (279, 'https://4b527230k9.zicp.fun/other/金线鱼.jpg');
INSERT INTO `fish_img` VALUES (280, 'https://4b527230k9.zicp.fun/other/深水金线鱼.jpg');
INSERT INTO `fish_img` VALUES (281, 'https://4b527230k9.zicp.fun/other/六带叉牙鯻.JPG');
INSERT INTO `fish_img` VALUES (282, 'https://4b527230k9.zicp.fun/other/细鳞鯻.jpg');
INSERT INTO `fish_img` VALUES (283, 'https://4b527230k9.zicp.fun/other/黑斑绯鲤.JPG');
INSERT INTO `fish_img` VALUES (284, 'https://4b527230k9.zicp.fun/other/双带副绯鲤.jpg');
INSERT INTO `fish_img` VALUES (285, 'https://4b527230k9.zicp.fun/other/燕鱼.png');
INSERT INTO `fish_img` VALUES (286, 'https://4b527230k9.zicp.fun/other/金钱鱼.JPG');
INSERT INTO `fish_img` VALUES (287, 'https://4b527230k9.zicp.fun/other/多纹钱鲽鱼.JPG');
INSERT INTO `fish_img` VALUES (288, 'https://4b527230k9.zicp.fun/other/多鳞四指马鲅.JPG');
INSERT INTO `fish_img` VALUES (289, 'https://4b527230k9.zicp.fun/other/弯角䲗.JPG');
INSERT INTO `fish_img` VALUES (290, 'https://4b527230k9.zicp.fun/other/褐蓝子鱼.jpg');
INSERT INTO `fish_img` VALUES (291, 'https://4b527230k9.zicp.fun/other/点蓝子鱼.jpg');
INSERT INTO `fish_img` VALUES (292, 'https://4b527230k9.zicp.fun/other/倒牙魣.jpg');
INSERT INTO `fish_img` VALUES (293, 'https://4b527230k9.zicp.fun/other/银鲳.png');
INSERT INTO `fish_img` VALUES (294, 'https://4b527230k9.zicp.fun/other/刺鲳.JPG');
INSERT INTO `fish_img` VALUES (295, 'https://4b527230k9.zicp.fun/other/拟矛尾刺虾虎鱼.png');
INSERT INTO `fish_img` VALUES (296, 'https://4b527230k9.zicp.fun/other/犬牙细棘虾虎鱼.jpg');
INSERT INTO `fish_img` VALUES (297, 'https://4b527230k9.zicp.fun/other/瞻星粗头鲉.jpg');
INSERT INTO `fish_img` VALUES (298, 'https://4b527230k9.zicp.fun/other/棘线鲬.jpg');
INSERT INTO `fish_img` VALUES (299, 'https://4b527230k9.zicp.fun/other/带纹条鳎.JPG');
INSERT INTO `fish_img` VALUES (300, 'https://4b527230k9.zicp.fun/other/斑头舌鳎.jpg');
INSERT INTO `fish_img` VALUES (301, 'https://4b527230k9.zicp.fun/other/黑鳍舌鳎.jpg');
INSERT INTO `fish_img` VALUES (302, 'https://4b527230k9.zicp.fun/other/卵鳎.jpg');
INSERT INTO `fish_img` VALUES (303, 'https://4b527230k9.zicp.fun/other/单角革鲀.jpg');
INSERT INTO `fish_img` VALUES (304, 'https://4b527230k9.zicp.fun/other/中华单角鲀.jpg');



